### ISSUE TITLE
Update Auth.net to v0.11.0 compatible

### ISSUE THREAD

**Issue by aaronjudd** [reactioncommerce/reaction-auth-net#2]
Update Auth.net to v0.7.0 compatible payment submit methods.

Add additional payment handling methods for v0.10.0 order workflow.

See: https://github.com/reactioncommerce/reaction-stripe/blob/development/lib/stripe.js

**Comment by aaronjudd** [comment]
See: https://github.com/reactioncommerce/reaction/issues/612

**Comment by zenweasel** [comment]
Includes rewrite and bug fixes.
